// 云函数入口文件
const cloud = require('wx-server-sdk')

cloud.init()

// 云函数入口函数
exports.main = async(event, context) => {

  const fundParam = ['name', 'EP', 'PE', 'PB', 'dividendYieldRatio', 'ROE', 'OnSiteFund', 'OTCFund'];

  const funds = [{
    name: '300价值',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: false,
    OTCFund: true
  }, {
    name: '50AH优选',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true
  }, {
    name: '上证红利',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: false
  }, {
    name: '中证银行',
    EP: false,
    PE: false,
    PB: true,
    dividendYieldRatio: true,
    ROE: false,
    OnSiteFund: true,
    OTCFund: true
  }, {
    name: '中证红利',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: false,
    OTCFund: true,
  }, {
    name: '基本面50',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '500低波动',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: 'H股指数',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '红利机会',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '上证50',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '基本面60',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '基本面120',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '证券行业',
    EP: false,
    PE: false,
    PB: true,
    dividendYieldRatio: false,
    ROE: false,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '中证养老',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: false,
    OTCFund: true,
  }, {
    name: '医药100',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: false,
    OTCFund: true,
  }, {
    name: '中证500',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '香港中小',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: false,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '央视50',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '上证180',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '可选消费',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '沪深300',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '深证100',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '恒生指数',
    EP: true,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '深证成指',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '中证消费',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '纳斯达克100',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: false,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '标普500',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: false,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '创业板',
    EP: false,
    PE: true,
    PB: true,
    dividendYieldRatio: true,
    ROE: true,
    OnSiteFund: true,
    OTCFund: true,
  }, {
    name: '十年期国债',
    EP: true,
    PE: false,
    PB: false,
    dividendYieldRatio: false,
    ROE: false,
    OnSiteFund: false,
    OTCFund: false,
  }, ];

  const param = {
    'date': {
      'regex': '20\\d{6}'
    },
    'EP': {
      'name': '盈利收益率',
      'des': '',
      'regex': '\\d+\\.\\d{2}%'
    },
    'PE': {
      'name': '市盈率',
      'des': '',
      'regex': '\\d+\\.\\d{2}'
    },
    'PB': {
      'name': '市净率',
      'des': '',
      'regex': '\\d+\\.\\d{2}'
    },
    'dividendYieldRatio': {
      'name': '股息率',
      'des': '',
      'regex': '\\d+\\.\\d{2}%'
    },
    'ROE': {
      'name': '企业运作资产效率',
      'des': '',
      'regex': '\\d+\\.\\d{2}%'
    },
    'OnSiteFund': {
      'name': '场内基金',
      'des': '',
      'regex': '\\d{6}'
    },
    'OTCFund': {
      'name': '场外基金',
      'des': '',
      'regex': '\\d{6}'
    }
  };

  return {
    funds,
    param,
    fundParam
  }
}